# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [dcramer, gr2m]
patreon: # Replace with a single Patreon username https://pornhub.com
open_collective: # Replace with a single Open Collective snaker.io
ko_fi: # Replace with a single Ko-fi username Mario
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username idgo 
otechie: # Replace with a single Otechie username investigate.tv
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['http://barbie.com', 'http://crest.com', 'http://Flonase.com', 'http://UPS.com', 'http://landstar.com','https://suave.com']
